### PR TITLE
Move variables to the last position in client methods for type inference

### PR DESCRIPTION
**Pull request by jeddeloh**
This is a proposed change to the shape of the client methods. The Operation module can't be in the last position or the types can't be inferred in order to pass the variables in as a record.

So this changes variables to be the last argument. I actually really like some things about this.

- Passing variables as last argument is consistent with the hooks that are on extended modules
- We can make variables required and it's not awkward when there are no variables (@jfrolich I think the decision to use `unit` for no variables was a great one!)
- Since making variables required isn't awkward we can just drop all the `0` functions

`T-first` _and_ a positional argument at the end is a bit odd and it's slightly awkward when you have all optional variables, but don't pass any, but I think that is extremely rare.

### CODE REVIEW

**Comment by jfrolich** [comment]
Awesome! I think `operation` (can be mutation or query) is perhaps not the right term when it's used specifically for a query or for a mutation. Perhaps we should use the argument `query` for the functions that operate on a query and `mutation` for functions that operate on a mutation. What do you think?

**Comment by jfrolich** [comment]
The only downside with remove the 0 functions is that when no variables are required (only optional variables) you still have to call `makeVariables` opposed to optional `variables` argument.

**Comment by jfrolich** [comment]
I still think this is probably fine, because with zero variables it's unit. And calling `Query.makeVariables()` as last argument is not that bad. We can also consider this for the hooks?

**Comment by jeddeloh** [comment]
> Awesome! I think operation (can be mutation or query) is perhaps not the right term when it's used specifically for a query or for a mutation. Perhaps we should use the argument query for the functions that operate on a query and mutation for functions that operate on a mutation. What do you think?

Yes! Good call. This is more in line with Apollo as well. 

> I still think this is probably fine, because with zero variables it's unit. And calling Query.makeVariables() as last argument is not that bad. We can also consider this for the hooks?

Yeah, I was thinking the same. Type inference only works with the extended modules right now.

**Pull request merged**
